<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net48</TargetFramework>
    <Platforms>x64</Platforms>
    <AssemblyName>WarmupSafezone</AssemblyName>
    <RootNamespace>ScpslPluginStarter</RootNamespace>
    <Version>1.0.0</Version>
    <PackageVersion>1.0.0</PackageVersion>
    <AssemblyVersion>1.0.0.0</AssemblyVersion>
    <FileVersion>1.0.0.0</FileVersion>
    <InformationalVersion>1.0.0</InformationalVersion>
    <IncludeSourceRevisionInInformationalVersion>false</IncludeSourceRevisionInInformationalVersion>
    <LangVersion>12.0</LangVersion>
    <Nullable>enable</Nullable>
    <DefaultItemExcludes>$(DefaultItemExcludes);tests\**</DefaultItemExcludes>
    <DisableImplicitFrameworkReferences>true</DisableImplicitFrameworkReferences>
    <ImplicitlyExpandDesignTimeFacades>false</ImplicitlyExpandDesignTimeFacades>
    <AssemblySearchPaths>$(SL_REFERENCES);$(AssemblySearchPaths)</AssemblySearchPaths>
  </PropertyGroup>

  <ItemGroup>
    <Reference Include="LabApi">
      <Private>false</Private>
    </Reference>
    <Reference Include="Assembly-CSharp">
      <Private>false</Private>
    </Reference>
    <Reference Include="Assembly-CSharp-firstpass">
      <Private>false</Private>
    </Reference>
    <Reference Include="CommandSystem.Core">
      <Private>false</Private>
    </Reference>
    <Reference Include="Mirror">
      <Private>false</Private>
    </Reference>
    <Reference Include="NorthwoodLib">
      <Private>false</Private>
    </Reference>
    <Reference Include="Pooling">
      <Private>false</Private>
    </Reference>
    <Reference Include="UnityEngine.CoreModule">
      <Private>false</Private>
    </Reference>
    <Reference Include="mscorlib" />
    <Reference Include="netstandard" />
    <Reference Include="System" />
    <Reference Include="System.Core" />
  </ItemGroup>

  <PropertyGroup>
    <_DeployTargetsFile>$([MSBuild]::GetPathOfFileAbove('Deploy.targets', '$(MSBuildProjectDirectory)'))</_DeployTargetsFile>
  </PropertyGroup>
  <Import Project="$(_DeployTargetsFile)" Condition="'$(_DeployTargetsFile)' != ''" />
</Project>
